version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Entered the install phase...
  pre_build:
    commands:
      - echo Entered the pre_build phase...
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
      - touch hoge.html
      - codebuild-breakpoint
artifacts:
  files:
    - hoge.html
